export {default as Brand} from './Brand'
export {default as Contact} from './Contact'
export {default as Highlight} from './Highlight'
export {default as PhotoGallery} from './PhotoGallery'
export {default as Testimonial} from './Testimonial'
export {default as NoRecordsFound} from './NoRecordsFound'